// <auto-generated />
using System;
using Kuvox.Api.Modules.Media.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kuvox.Api.Modules.Media.Repositories.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    [Migration("20260705093000_AddMediaAlbumAccessHiddenFlags")]
    partial class AddMediaAlbumAccessHiddenFlags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("media")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kuvox.Api.Modules.Media.Models.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsDeleteAble")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MaterialSymbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerKind", "OwnerId");

                    b.ToTable("albums", "media");
                });

            modelBuilder.Entity("Kuvox.Api.Modules.Media.Models.AlbumMedia", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AlbumId", "MediaId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Kuvox.Api.Modules.Media.Models.AlbumUser", b =>
                {
                    b.Property<Guid>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AlbumId", "UserId");

                    b.ToTable("album_users", "media");
                });

            modelBuilder.Entity("Kuvox.Api.Modules.Media.Models.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchiveReason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("ArchiveStorageKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CanonicalBucketName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("CanonicalSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("CanonicalStorageKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Codec")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProxyBucketName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("ProxySizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ProxyStorageKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("RawBucketName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("RawSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("RawStorageKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("ThumbnailBucketName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("ThumbnailSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ThumbnailStorageKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Kuvox.Api.Modules.Media.Models.MediaUser", b =>
                {
                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MediaId", "UserId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Kuvox.Api.Modules.Shared.Infrastructure.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("DedupeKey")
                        .IsUnique();

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("outbox_messages", "shared");
                });

            modelBuilder.Entity("Kuvox.Api.Modules.Media.Models.AlbumAudio", b =>
                {
                    b.HasBaseType("Kuvox.Api.Modules.Media.Models.AlbumMedia");

                    b.HasIndex("MediaId");

                    b.ToTable("album_audios", "media");
                });

            modelBuilder.Entity("Kuvox.Api.Modules.Media.Models.AlbumPhoto", b =>
                {
                    b.HasBaseType("Kuvox.Api.Modules.Media.Models.AlbumMedia");

                    b.HasIndex("MediaId");

                    b.ToTable("album_photos", "media");
                });

            modelBuilder.Entity("Kuvox.Api.Modules.Media.Models.AlbumVideo", b =>
                {
                    b.HasBaseType("Kuvox.Api.Modules.Media.Models.AlbumMedia");

                    b.HasIndex("MediaId");

                    b.ToTable("album_videos", "media");
                });

            modelBuilder.Entity("Kuvox.Api.Modules.Media.Models.Audio", b =>
                {
                    b.HasBaseType("Kuvox.Api.Modules.Media.Models.Media");

                    b.Property<double>("DurationSeconds")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("OwnerKind", "OwnerId");

                    b.ToTable("audios", "media");
                });

            modelBuilder.Entity("Kuvox.Api.Modules.Media.Models.Photo", b =>
                {
                    b.HasBaseType("Kuvox.Api.Modules.Media.Models.Media");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("OwnerKind", "OwnerId");

                    b.ToTable("photos", "media");
                });

            modelBuilder.Entity("Kuvox.Api.Modules.Media.Models.Video", b =>
                {
                    b.HasBaseType("Kuvox.Api.Modules.Media.Models.Media");

                    b.Property<double>("DurationSeconds")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<double>("FrameRate")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("OwnerKind", "OwnerId");

                    b.ToTable("videos", "media");
                });

            modelBuilder.Entity("Kuvox.Api.Modules.Media.Models.AudioUser", b =>
                {
                    b.HasBaseType("Kuvox.Api.Modules.Media.Models.MediaUser");

                    b.HasIndex("UserId");

                    b.ToTable("audio_users", "media");
                });

            modelBuilder.Entity("Kuvox.Api.Modules.Media.Models.PhotoUser", b =>
                {
                    b.HasBaseType("Kuvox.Api.Modules.Media.Models.MediaUser");

                    b.HasIndex("UserId");

                    b.ToTable("photo_users", "media");
                });

            modelBuilder.Entity("Kuvox.Api.Modules.Media.Models.VideoUser", b =>
                {
                    b.HasBaseType("Kuvox.Api.Modules.Media.Models.MediaUser");

                    b.HasIndex("UserId");

                    b.ToTable("video_users", "media");
                });

            modelBuilder.Entity("Kuvox.Api.Modules.Media.Models.AlbumUser", b =>
                {
                    b.HasOne("Kuvox.Api.Modules.Media.Models.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kuvox.Api.Modules.Media.Models.AlbumAudio", b =>
                {
                    b.HasOne("Kuvox.Api.Modules.Media.Models.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kuvox.Api.Modules.Media.Models.Audio", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kuvox.Api.Modules.Media.Models.AlbumPhoto", b =>
                {
                    b.HasOne("Kuvox.Api.Modules.Media.Models.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kuvox.Api.Modules.Media.Models.Photo", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kuvox.Api.Modules.Media.Models.AlbumVideo", b =>
                {
                    b.HasOne("Kuvox.Api.Modules.Media.Models.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kuvox.Api.Modules.Media.Models.Video", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kuvox.Api.Modules.Media.Models.AudioUser", b =>
                {
                    b.HasOne("Kuvox.Api.Modules.Media.Models.Audio", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kuvox.Api.Modules.Media.Models.PhotoUser", b =>
                {
                    b.HasOne("Kuvox.Api.Modules.Media.Models.Photo", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kuvox.Api.Modules.Media.Models.VideoUser", b =>
                {
                    b.HasOne("Kuvox.Api.Modules.Media.Models.Video", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
